#!/usr/bin/env python3
"""
Python Project Generator
Generates a Python project based on issue metadata
"""

import os
import sys
import json
import re
from pathlib import Path


def parse_issue_body(issue_body):
    """Parse issue body to extract configuration"""
    config = {}
    
    # Extract framework
    framework_match = re.search(r'### Framework\s*\n\s*(.+)', issue_body)
    config['framework'] = framework_match.group(1).strip() if framework_match else 'Django'
    
    # Extract database
    db_match = re.search(r'### Database\s*\n\s*(.+)', issue_body)
    config['database'] = db_match.group(1).strip() if db_match else 'SQLite'
    
    # Extract description
    desc_match = re.search(r'### Project Description\s*\n\s*(.+)', issue_body, re.DOTALL)
    config['description'] = desc_match.group(1).strip() if desc_match else ''
    
    # Extract features
    config['features'] = []
    if 'User Authentication' in issue_body:
        config['features'].append('auth')
    if 'REST API' in issue_body:
        config['features'].append('rest_api')
    if 'GraphQL API' in issue_body:
        config['features'].append('graphql')
    if 'Celery' in issue_body:
        config['features'].append('celery')
    if 'Docker Support' in issue_body:
        config['features'].append('docker')
    if 'Unit Tests' in issue_body:
        config['features'].append('tests')
    
    return config


def generate_django_project(project_name, config, output_dir):
    """Generate Django project structure"""
    print(f"Generating Django project: {project_name}")
    
    # Create project structure
    project_path = output_dir / project_name
    project_path.mkdir(parents=True, exist_ok=True)
    
    # Create requirements.txt
    requirements = [
        'Django==4.2.0',
        'djangorestframework==3.14.0',
        'python-decouple==3.8',
    ]
    
    if config['database'] == 'MongoDB':
        requirements.append('djongo==1.3.6')
        requirements.append('pymongo==3.12')
    elif config['database'] == 'PostgreSQL':
        requirements.append('psycopg2-binary==2.9.9')
    elif config['database'] == 'MySQL':
        requirements.append('mysqlclient==2.2.0')
    
    if 'auth' in config['features']:
        requirements.append('django-allauth==0.57.0')
        requirements.append('dj-rest-auth==5.0.0')
    
    if 'graphql' in config['features']:
        requirements.append('graphene-django==3.1.5')
    
    if 'celery' in config['features']:
        requirements.append('celery==5.3.4')
        requirements.append('redis==5.0.1')
    
    if 'docker' in config['features']:
        requirements.append('gunicorn==21.2.0')
    
    (project_path / 'requirements.txt').write_text('\n'.join(requirements))
    
    # Create README.md
    readme_content = f"""# {project_name}

{config['description']}

## Framework
- Django 4.2
- Database: {config['database']}

## Features
{chr(10).join(f'- {feature}' for feature in config['features'])}

## Setup

### Install dependencies
```bash
python -m venv venv
source venv/bin/activate  # On Windows: venv\\Scripts\\activate
pip install -r requirements.txt
```

### Initialize database
```bash
python manage.py migrate
python manage.py createsuperuser
```

### Run development server
```bash
python manage.py runserver
```

## API Documentation
Visit `/api/docs/` for interactive API documentation (if REST API is enabled).

## Testing
```bash
python manage.py test
```

## Generated by CodeGen Automator
This project was automatically generated based on your requirements.
"""
    (project_path / 'README.md').write_text(readme_content)
    
    # Create manage.py
    (project_path / 'manage.py').write_text("""#!/usr/bin/env python
import os
import sys

if __name__ == '__main__':
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed?"
        ) from exc
    execute_from_command_line(sys.argv)
""")
    
    # Create config directory
    config_dir = project_path / 'config'
    config_dir.mkdir(exist_ok=True)
    (config_dir / '__init__.py').write_text('')
    
    # Create settings.py
    db_config = {
        'SQLite': "DATABASES = {\n    'default': {\n        'ENGINE': 'django.db.backends.sqlite3',\n        'NAME': BASE_DIR / 'db.sqlite3',\n    }\n}",
        'PostgreSQL': "DATABASES = {\n    'default': {\n        'ENGINE': 'django.db.backends.postgresql',\n        'NAME': config('DB_NAME', default='mydb'),\n        'USER': config('DB_USER', default='postgres'),\n        'PASSWORD': config('DB_PASSWORD', default='password'),\n        'HOST': config('DB_HOST', default='localhost'),\n        'PORT': config('DB_PORT', default='5432'),\n    }\n}",
        'MySQL': "DATABASES = {\n    'default': {\n        'ENGINE': 'django.db.backends.mysql',\n        'NAME': config('DB_NAME', default='mydb'),\n        'USER': config('DB_USER', default='root'),\n        'PASSWORD': config('DB_PASSWORD', default='password'),\n        'HOST': config('DB_HOST', default='localhost'),\n        'PORT': config('DB_PORT', default='3306'),\n    }\n}",
    }
    
    settings_content = f"""from pathlib import Path
from decouple import config

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = config('SECRET_KEY', default='django-insecure-change-this-in-production')

DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*').split(',')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {{
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {{
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        }},
    }},
]

WSGI_APPLICATION = 'config.wsgi.application'

{db_config.get(config['database'], db_config['SQLite'])}

AUTH_PASSWORD_VALIDATORS = [
    {{'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'}},
    {{'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'}},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {{
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}}
"""
    (config_dir / 'settings.py').write_text(settings_content)
    
    # Create urls.py
    urls_content = """from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
]
"""
    (config_dir / 'urls.py').write_text(urls_content)
    
    # Create wsgi.py
    wsgi_content = """import os
from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
application = get_wsgi_application()
"""
    (config_dir / 'wsgi.py').write_text(wsgi_content)
    
    # Create API app
    api_dir = project_path / 'api'
    api_dir.mkdir(exist_ok=True)
    (api_dir / '__init__.py').write_text('')
    (api_dir / 'apps.py').write_text("""from django.apps import AppConfig

class ApiConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'api'
""")
    (api_dir / 'models.py').write_text("""from django.db import models

class SampleModel(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['-created_at']
""")
    (api_dir / 'serializers.py').write_text("""from rest_framework import serializers
from .models import SampleModel

class SampleSerializer(serializers.ModelSerializer):
    class Meta:
        model = SampleModel
        fields = '__all__'
""")
    (api_dir / 'views.py').write_text("""from rest_framework import viewsets
from .models import SampleModel
from .serializers import SampleSerializer

class SampleViewSet(viewsets.ModelViewSet):
    queryset = SampleModel.objects.all()
    serializer_class = SampleSerializer
""")
    (api_dir / 'urls.py').write_text("""from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import SampleViewSet

router = DefaultRouter()
router.register(r'samples', SampleViewSet)

urlpatterns = [
    path('', include(router.urls)),
]
""")
    (api_dir / 'admin.py').write_text("""from django.contrib import admin
from .models import SampleModel

@admin.register(SampleModel)
class SampleModelAdmin(admin.ModelAdmin):
    list_display = ['name', 'created_at', 'updated_at']
    search_fields = ['name', 'description']
""")
    (api_dir / 'tests.py').write_text("""from django.test import TestCase
from .models import SampleModel

class SampleModelTestCase(TestCase):
    def setUp(self):
        SampleModel.objects.create(name="Test Item", description="Test Description")
    
    def test_sample_creation(self):
        item = SampleModel.objects.get(name="Test Item")
        self.assertEqual(item.description, "Test Description")
""")
    
    # Create .gitignore
    gitignore_content = """# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
venv/
env/
ENV/

# Django
*.log
db.sqlite3
media/
staticfiles/

# IDE
.vscode/
.idea/
*.swp

# Environment
.env
.env.local
"""
    (project_path / '.gitignore').write_text(gitignore_content)
    
    # Create Docker files if needed
    if 'docker' in config['features']:
        dockerfile_content = f"""FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "config.wsgi:application"]
"""
        (project_path / 'Dockerfile').write_text(dockerfile_content)
        
        docker_compose_content = f"""version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
"""
        (project_path / 'docker-compose.yml').write_text(docker_compose_content)
    
    print(f"✅ Django project created at {project_path}")


def generate_flask_project(project_name, config, output_dir):
    """Generate Flask project structure"""
    print(f"Generating Flask project: {project_name}")
    
    project_path = output_dir / project_name
    project_path.mkdir(parents=True, exist_ok=True)
    
    # Create requirements.txt
    requirements = [
        'Flask==3.0.0',
        'Flask-RESTful==0.3.10',
        'python-decouple==3.8',
    ]
    
    if config['database'] == 'PostgreSQL':
        requirements.append('psycopg2-binary==2.9.9')
        requirements.append('Flask-SQLAlchemy==3.1.1')
    elif config['database'] == 'MongoDB':
        requirements.append('Flask-PyMongo==2.3.0')
        requirements.append('pymongo==4.6.0')
    
    if 'auth' in config['features']:
        requirements.append('Flask-JWT-Extended==4.5.3')
    
    (project_path / 'requirements.txt').write_text('\n'.join(requirements))
    
    # Create README.md
    readme_content = f"""# {project_name}

{config['description']}

## Framework
- Flask 3.0
- Database: {config['database']}

## Features
{chr(10).join(f'- {feature}' for feature in config['features'])}

## Setup

```bash
python -m venv venv
source venv/bin/activate
pip install -r requirements.txt
python app.py
```

## Generated by CodeGen Automator
"""
    (project_path / 'README.md').write_text(readme_content)
    
    # Create app.py with complete structure
    app_content = """from flask import Flask, jsonify
from flask_restful import Api, Resource
from decouple import config

app = Flask(__name__)
app.config['SECRET_KEY'] = config('SECRET_KEY', default='dev-secret-key-change-in-production')
app.config['DEBUG'] = config('DEBUG', default=True, cast=bool)

api = Api(app)

# Sample data store (replace with database in production)
items = [
    {'id': 1, 'name': 'Sample Item 1', 'description': 'First sample item'},
    {'id': 2, 'name': 'Sample Item 2', 'description': 'Second sample item'},
]

class ItemList(Resource):
    def get(self):
        return {'items': items}, 200
    
    def post(self):
        # In production, parse request data and add to database
        return {'message': 'Item created'}, 201

class Item(Resource):
    def get(self, item_id):
        item = next((item for item in items if item['id'] == item_id), None)
        if item:
            return item, 200
        return {'message': 'Item not found'}, 404
    
    def put(self, item_id):
        # In production, update database
        return {'message': 'Item updated'}, 200
    
    def delete(self, item_id):
        # In production, delete from database
        return {'message': 'Item deleted'}, 204

@app.route('/')
def index():
    return jsonify({
        'message': 'Welcome to {project_name} API',
        'endpoints': [
            '/api/items',
            '/api/items/<int:item_id>'
        ]
    })

@app.route('/health')
def health():
    return jsonify({'status': 'healthy'}), 200

api.add_resource(ItemList, '/api/items')
api.add_resource(Item, '/api/items/<int:item_id>')

if __name__ == '__main__':
    app.run(
        host=config('HOST', default='0.0.0.0'),
        port=config('PORT', default=5000, cast=int),
        debug=config('DEBUG', default=True, cast=bool)
    )
"""
    (project_path / 'app.py').write_text(app_content)
    
    # Create .env file
    env_content = """SECRET_KEY=your-secret-key-here-change-in-production
DEBUG=True
HOST=0.0.0.0
PORT=5000
"""
    (project_path / '.env').write_text(env_content)
    
    # Create .gitignore
    gitignore_content = """# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
venv/
env/
ENV/
.venv

# Environment
.env
.env.local

# IDE
.vscode/
.idea/
*.swp
*.swo
"""
    (project_path / '.gitignore').write_text(gitignore_content)
    
    print(f"✅ Flask project created at {project_path}")


def generate_fastapi_project(project_name, config, output_dir):
    """Generate FastAPI project structure"""
    print(f"Generating FastAPI project: {project_name}")
    
    project_path = output_dir / project_name
    project_path.mkdir(parents=True, exist_ok=True)
    
    # Create requirements.txt
    requirements = [
        'fastapi==0.104.0',
        'uvicorn[standard]==0.24.0',
        'pydantic==2.5.0',
        'python-decouple==3.8',
    ]
    
    if config['database'] == 'PostgreSQL':
        requirements.append('sqlalchemy==2.0.23')
        requirements.append('psycopg2-binary==2.9.9')
    elif config['database'] == 'MongoDB':
        requirements.append('motor==3.3.2')
        requirements.append('pymongo==4.6.0')
    
    if 'auth' in config['features']:
        requirements.append('python-jose[cryptography]==3.3.0')
        requirements.append('passlib[bcrypt]==1.7.4')
    
    (project_path / 'requirements.txt').write_text('\n'.join(requirements))
    
    # Create README.md
    readme_content = f"""# {project_name}

{config['description']}

## Framework
- FastAPI
- Database: {config['database']}

## Features
{chr(10).join(f'- {feature}' for feature in config['features'])}

## Setup

```bash
python -m venv venv
source venv/bin/activate
pip install -r requirements.txt
uvicorn main:app --reload
```

Visit http://localhost:8000/docs for API documentation.

## Generated by CodeGen Automator
"""
    (project_path / 'README.md').write_text(readme_content)
    
    # Create main.py with complete API structure
    main_content = f"""from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional
from datetime import datetime
from decouple import config

app = FastAPI(
    title="{project_name}",
    description="{config['description']}",
    version="1.0.0"
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Configure appropriately in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Pydantic models
class ItemBase(BaseModel):
    name: str
    description: Optional[str] = None

class ItemCreate(ItemBase):
    pass

class ItemUpdate(ItemBase):
    pass

class Item(ItemBase):
    id: int
    created_at: datetime
    updated_at: datetime
    
    class Config:
        from_attributes = True

# In-memory database (replace with real database in production)
items_db = [
    {{
        "id": 1,
        "name": "Sample Item 1",
        "description": "First sample item",
        "created_at": datetime.now(),
        "updated_at": datetime.now()
    }},
    {{
        "id": 2,
        "name": "Sample Item 2",
        "description": "Second sample item",
        "created_at": datetime.now(),
        "updated_at": datetime.now()
    }}
]

@app.get("/")
def read_root():
    return {{
        "message": "Welcome to {project_name} API",
        "docs": "/docs",
        "endpoints": ["/api/items", "/api/items/{{item_id}}", "/health"]
    }}

@app.get("/health")
def health_check():
    return {{"status": "healthy", "timestamp": datetime.now()}}

@app.get("/api/items", response_model=List[Item])
def get_items(skip: int = 0, limit: int = 100):
    return items_db[skip : skip + limit]

@app.get("/api/items/{{item_id}}", response_model=Item)
def get_item(item_id: int):
    item = next((item for item in items_db if item["id"] == item_id), None)
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    return item

@app.post("/api/items", response_model=Item, status_code=201)
def create_item(item: ItemCreate):
    new_id = max([i["id"] for i in items_db]) + 1 if items_db else 1
    new_item = {{
        "id": new_id,
        "name": item.name,
        "description": item.description,
        "created_at": datetime.now(),
        "updated_at": datetime.now()
    }}
    items_db.append(new_item)
    return new_item

@app.put("/api/items/{{item_id}}", response_model=Item)
def update_item(item_id: int, item: ItemUpdate):
    db_item = next((item for item in items_db if item["id"] == item_id), None)
    if not db_item:
        raise HTTPException(status_code=404, detail="Item not found")
    
    db_item["name"] = item.name
    db_item["description"] = item.description
    db_item["updated_at"] = datetime.now()
    return db_item

@app.delete("/api/items/{{item_id}}", status_code=204)
def delete_item(item_id: int):
    global items_db
    items_db = [item for item in items_db if item["id"] != item_id]
    return None

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(
        "main:app",
        host=config("HOST", default="0.0.0.0"),
        port=config("PORT", default=8000, cast=int),
        reload=config("DEBUG", default=True, cast=bool)
    )
"""
    (project_path / 'main.py').write_text(main_content)
    
    # Create .env file
    env_content = """DEBUG=True
HOST=0.0.0.0
PORT=8000
SECRET_KEY=your-secret-key-here-change-in-production
"""
    (project_path / '.env').write_text(env_content)
    
    # Create .gitignore
    gitignore_content = """# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
venv/
env/
ENV/
.venv

# Environment
.env
.env.local

# IDE
.vscode/
.idea/
*.swp
*.swo

# Database
*.db
*.sqlite3
"""
    (project_path / '.gitignore').write_text(gitignore_content)
    
    # Create models.py for database models (if using SQLAlchemy)
    if config['database'] in ['PostgreSQL', 'MySQL', 'SQLite']:
        models_content = """from sqlalchemy import Column, Integer, String, Text, DateTime
from sqlalchemy.ext.declarative import declarative_base
from datetime import datetime

Base = declarative_base()

class Item(Base):
    __tablename__ = "items"
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(200), nullable=False)
    description = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
"""
        (project_path / 'models.py').write_text(models_content)
        
        # Create database.py
        database_content = """from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from decouple import config

DATABASE_URL = config("DATABASE_URL", default="sqlite:///./app.db")

engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False} if "sqlite" in DATABASE_URL else {})
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
"""
        (project_path / 'database.py').write_text(database_content)
    
    print(f"✅ FastAPI project created at {project_path}")


def main():
    if len(sys.argv) < 3:
        print("Usage: generate-python.py <project_name> <metadata_file>")
        sys.exit(1)
    
    project_name = sys.argv[1]
    metadata_file = sys.argv[2]
    
    # Read metadata
    with open(metadata_file, 'r') as f:
        metadata = json.load(f)
    
    issue_body = metadata['issue_body']
    config = parse_issue_body(issue_body)
    
    print(f"Configuration: {json.dumps(config, indent=2)}")
    
    # Determine output directory
    output_dir = Path('generated-projects')
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Generate project based on framework
    framework = config['framework'].lower()
    if 'django' in framework:
        generate_django_project(project_name, config, output_dir)
    elif 'flask' in framework:
        generate_flask_project(project_name, config, output_dir)
    elif 'fastapi' in framework:
        generate_fastapi_project(project_name, config, output_dir)
    else:
        print(f"Unknown framework: {framework}")
        sys.exit(1)


if __name__ == '__main__':
    main()
