#!/usr/bin/env python3
"""
Python Project Generator
Generates a Python project based on issue metadata
"""

import os
import sys
import json
import re
from pathlib import Path


def parse_issue_body(issue_body):
    """Parse issue body to extract configuration"""
    config = {}
    
    # Extract framework
    framework_match = re.search(r'### Framework\s*\n\s*(.+)', issue_body)
    config['framework'] = framework_match.group(1).strip() if framework_match else 'Django'
    
    # Extract database
    db_match = re.search(r'### Database\s*\n\s*(.+)', issue_body)
    config['database'] = db_match.group(1).strip() if db_match else 'SQLite'
    
    # Extract description
    desc_match = re.search(r'### Project Description\s*\n\s*(.+)', issue_body, re.DOTALL)
    config['description'] = desc_match.group(1).strip() if desc_match else ''
    
    # Extract features
    config['features'] = []
    if 'User Authentication' in issue_body:
        config['features'].append('auth')
    if 'REST API' in issue_body:
        config['features'].append('rest_api')
    if 'GraphQL API' in issue_body:
        config['features'].append('graphql')
    if 'Celery' in issue_body:
        config['features'].append('celery')
    if 'Docker Support' in issue_body:
        config['features'].append('docker')
    if 'Unit Tests' in issue_body:
        config['features'].append('tests')
    
    return config


def generate_django_project(project_name, config, output_dir):
    """Generate Django project structure"""
    print(f"Generating Django project: {project_name}")
    
    # Create project structure
    project_path = output_dir / project_name
    project_path.mkdir(parents=True, exist_ok=True)
    
    # Create requirements.txt
    requirements = [
        'Django==4.2.0',
        'djangorestframework==3.14.0',
        'python-decouple==3.8',
    ]
    
    if config['database'] == 'MongoDB':
        requirements.append('djongo==1.3.6')
        requirements.append('pymongo==3.12')
    elif config['database'] == 'PostgreSQL':
        requirements.append('psycopg2-binary==2.9.9')
    elif config['database'] == 'MySQL':
        requirements.append('mysqlclient==2.2.0')
    
    if 'auth' in config['features']:
        requirements.append('django-allauth==0.57.0')
        requirements.append('dj-rest-auth==5.0.0')
    
    if 'graphql' in config['features']:
        requirements.append('graphene-django==3.1.5')
    
    if 'celery' in config['features']:
        requirements.append('celery==5.3.4')
        requirements.append('redis==5.0.1')
    
    if 'docker' in config['features']:
        requirements.append('gunicorn==21.2.0')
    
    (project_path / 'requirements.txt').write_text('\n'.join(requirements))
    
    # Create README.md
    readme_content = f"""# {project_name}

{config['description']}

## Framework
- Django 4.2
- Database: {config['database']}

## Features
{chr(10).join(f'- {feature}' for feature in config['features'])}

## Setup

### Install dependencies
```bash
python -m venv venv
source venv/bin/activate  # On Windows: venv\\Scripts\\activate
pip install -r requirements.txt
```

### Initialize database
```bash
python manage.py migrate
python manage.py createsuperuser
```

### Run development server
```bash
python manage.py runserver
```

## API Documentation
Visit `/api/docs/` for interactive API documentation (if REST API is enabled).

## Testing
```bash
python manage.py test
```

## Generated by CodeGen Automator
This project was automatically generated based on your requirements.
"""
    (project_path / 'README.md').write_text(readme_content)
    
    # Create basic Django structure placeholders
    (project_path / 'manage.py').write_text("""#!/usr/bin/env python
import os
import sys

if __name__ == '__main__':
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed?"
        ) from exc
    execute_from_command_line(sys.argv)
""")
    
    # Create .gitignore
    gitignore_content = """# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
venv/
env/
ENV/

# Django
*.log
db.sqlite3
media/
staticfiles/

# IDE
.vscode/
.idea/
*.swp

# Environment
.env
.env.local
"""
    (project_path / '.gitignore').write_text(gitignore_content)
    
    # Create Docker files if needed
    if 'docker' in config['features']:
        dockerfile_content = f"""FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "config.wsgi:application"]
"""
        (project_path / 'Dockerfile').write_text(dockerfile_content)
        
        docker_compose_content = f"""version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
"""
        (project_path / 'docker-compose.yml').write_text(docker_compose_content)
    
    print(f"✅ Django project created at {project_path}")


def generate_flask_project(project_name, config, output_dir):
    """Generate Flask project structure"""
    print(f"Generating Flask project: {project_name}")
    
    project_path = output_dir / project_name
    project_path.mkdir(parents=True, exist_ok=True)
    
    # Create requirements.txt
    requirements = [
        'Flask==3.0.0',
        'Flask-RESTful==0.3.10',
        'python-decouple==3.8',
    ]
    
    if config['database'] == 'PostgreSQL':
        requirements.append('psycopg2-binary==2.9.9')
        requirements.append('Flask-SQLAlchemy==3.1.1')
    elif config['database'] == 'MongoDB':
        requirements.append('Flask-PyMongo==2.3.0')
        requirements.append('pymongo==4.6.0')
    
    if 'auth' in config['features']:
        requirements.append('Flask-JWT-Extended==4.5.3')
    
    (project_path / 'requirements.txt').write_text('\n'.join(requirements))
    
    # Create README.md
    readme_content = f"""# {project_name}

{config['description']}

## Framework
- Flask 3.0
- Database: {config['database']}

## Features
{chr(10).join(f'- {feature}' for feature in config['features'])}

## Setup

```bash
python -m venv venv
source venv/bin/activate
pip install -r requirements.txt
python app.py
```

## Generated by CodeGen Automator
"""
    (project_path / 'README.md').write_text(readme_content)
    
    # Create basic app.py
    app_content = """from flask import Flask

app = Flask(__name__)

@app.route('/')
def hello():
    return {'message': 'Hello from Flask!'}

if __name__ == '__main__':
    app.run(debug=True)
"""
    (project_path / 'app.py').write_text(app_content)
    
    print(f"✅ Flask project created at {project_path}")


def generate_fastapi_project(project_name, config, output_dir):
    """Generate FastAPI project structure"""
    print(f"Generating FastAPI project: {project_name}")
    
    project_path = output_dir / project_name
    project_path.mkdir(parents=True, exist_ok=True)
    
    # Create requirements.txt
    requirements = [
        'fastapi==0.104.0',
        'uvicorn[standard]==0.24.0',
        'pydantic==2.5.0',
        'python-decouple==3.8',
    ]
    
    if config['database'] == 'PostgreSQL':
        requirements.append('sqlalchemy==2.0.23')
        requirements.append('psycopg2-binary==2.9.9')
    elif config['database'] == 'MongoDB':
        requirements.append('motor==3.3.2')
        requirements.append('pymongo==4.6.0')
    
    if 'auth' in config['features']:
        requirements.append('python-jose[cryptography]==3.3.0')
        requirements.append('passlib[bcrypt]==1.7.4')
    
    (project_path / 'requirements.txt').write_text('\n'.join(requirements))
    
    # Create README.md
    readme_content = f"""# {project_name}

{config['description']}

## Framework
- FastAPI
- Database: {config['database']}

## Features
{chr(10).join(f'- {feature}' for feature in config['features'])}

## Setup

```bash
python -m venv venv
source venv/bin/activate
pip install -r requirements.txt
uvicorn main:app --reload
```

Visit http://localhost:8000/docs for API documentation.

## Generated by CodeGen Automator
"""
    (project_path / 'README.md').write_text(readme_content)
    
    # Create main.py
    main_content = """from fastapi import FastAPI

app = FastAPI(title="Generated API", version="1.0.0")

@app.get("/")
def read_root():
    return {"message": "Hello from FastAPI!"}

@app.get("/health")
def health_check():
    return {"status": "healthy"}
"""
    (project_path / 'main.py').write_text(main_content)
    
    print(f"✅ FastAPI project created at {project_path}")


def main():
    if len(sys.argv) < 3:
        print("Usage: generate-python.py <project_name> <metadata_file>")
        sys.exit(1)
    
    project_name = sys.argv[1]
    metadata_file = sys.argv[2]
    
    # Read metadata
    with open(metadata_file, 'r') as f:
        metadata = json.load(f)
    
    issue_body = metadata['issue_body']
    config = parse_issue_body(issue_body)
    
    print(f"Configuration: {json.dumps(config, indent=2)}")
    
    # Determine output directory
    output_dir = Path('generated-projects')
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Generate project based on framework
    framework = config['framework'].lower()
    if 'django' in framework:
        generate_django_project(project_name, config, output_dir)
    elif 'flask' in framework:
        generate_flask_project(project_name, config, output_dir)
    elif 'fastapi' in framework:
        generate_fastapi_project(project_name, config, output_dir)
    else:
        print(f"Unknown framework: {framework}")
        sys.exit(1)


if __name__ == '__main__':
    main()
