#!/usr/bin/env python3

"""
Modify existing Python projects
Applies changes to existing FastAPI/Flask/Django projects in different repositories
"""

import json
import os
import sys
from pathlib import Path

def detect_python_framework(project_path):
    """Detect which Python framework is being used"""
    if Path(project_path, 'manage.py').exists():
        return 'django'
    
    main_files = list(Path(project_path).glob('**/main.py'))
    for main_file in main_files:
        content = main_file.read_text()
        if 'FastAPI' in content or 'fastapi' in content:
            return 'fastapi'
        if 'Flask' in content or 'flask' in content:
            return 'flask'
    
    return 'unknown'

def add_fastapi_endpoint(project_path, modifications):
    """Add new endpoint to FastAPI project"""
    description = modifications.get('description', '')
    
    # Create API route file
    api_dir = Path(project_path, 'app/api/routes')
    api_dir.mkdir(parents=True, exist_ok=True)
    
    # Extract feature name from description
    feature_name = 'new_feature'
    if 'auth' in description.lower():
        feature_name = 'auth'
    elif 'user' in description.lower():
        feature_name = 'users'
    
    route_file = api_dir / f'{feature_name}.py'
    
    route_content = f'''"""
{feature_name.title()} API endpoints
Auto-generated by CodeGen Automator
"""

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from typing import List

from app.core.database import get_db
from app.models.schemas import {feature_name.title()}Create, {feature_name.title()}Response
from app.services.{feature_name}_service import {feature_name.title()}Service

router = APIRouter(prefix="/{feature_name}", tags=["{feature_name}"])

@router.post("/", response_model={feature_name.title()}Response, status_code=status.HTTP_201_CREATED)
async def create_{feature_name}(
    data: {feature_name.title()}Create,
    db: Session = Depends(get_db)
):
    """Create new {feature_name}"""
    service = {feature_name.title()}Service(db)
    return await service.create(data)

@router.get("/", response_model=List[{feature_name.title()}Response])
async def list_{feature_name}(
    skip: int = 0,
    limit: int = 100,
    db: Session = Depends(get_db)
):
    """List all {feature_name}"""
    service = {feature_name.title()}Service(db)
    return await service.list(skip=skip, limit=limit)

@router.get("/{{item_id}}", response_model={feature_name.title()}Response)
async def get_{feature_name}(
    item_id: int,
    db: Session = Depends(get_db)
):
    """Get {feature_name} by ID"""
    service = {feature_name.title()}Service(db)
    item = await service.get(item_id)
    if not item:
        raise HTTPException(status_code=404, detail="{feature_name.title()} not found")
    return item
'''
    
    route_file.write_text(route_content)
    print(f"✓ Created API route: {route_file}")
    
    # Create service file
    service_dir = Path(project_path, 'app/services')
    service_dir.mkdir(parents=True, exist_ok=True)
    
    service_file = service_dir / f'{feature_name}_service.py'
    service_content = f'''"""
{feature_name.title()} business logic service
"""

from sqlalchemy.orm import Session
from typing import List, Optional

from app.models.domain import {feature_name.title()}
from app.repositories.{feature_name}_repository import {feature_name.title()}Repository

class {feature_name.title()}Service:
    def __init__(self, db: Session):
        self.repository = {feature_name.title()}Repository(db)
    
    async def create(self, data):
        """Create new {feature_name}"""
        return await self.repository.create(data)
    
    async def get(self, item_id: int) -> Optional[{feature_name.title()}]:
        """Get {feature_name} by ID"""
        return await self.repository.get(item_id)
    
    async def list(self, skip: int = 0, limit: int = 100) -> List[{feature_name.title()}]:
        """List {feature_name}"""
        return await self.repository.list(skip, limit)
    
    async def update(self, item_id: int, data):
        """Update {feature_name}"""
        return await self.repository.update(item_id, data)
    
    async def delete(self, item_id: int):
        """Delete {feature_name}"""
        return await self.repository.delete(item_id)
'''
    
    service_file.write_text(service_content)
    print(f"✓ Created service: {service_file}")
    
    # Create repository file
    repo_dir = Path(project_path, 'app/repositories')
    repo_dir.mkdir(parents=True, exist_ok=True)
    
    repo_file = repo_dir / f'{feature_name}_repository.py'
    repo_content = f'''"""
{feature_name.title()} data access repository
"""

from sqlalchemy.orm import Session
from typing import List, Optional

from app.models.domain import {feature_name.title()}

class {feature_name.title()}Repository:
    def __init__(self, db: Session):
        self.db = db
    
    async def create(self, data) -> {feature_name.title()}:
        """Create new record"""
        db_item = {feature_name.title()}(**data.dict())
        self.db.add(db_item)
        self.db.commit()
        self.db.refresh(db_item)
        return db_item
    
    async def get(self, item_id: int) -> Optional[{feature_name.title()}]:
        """Get record by ID"""
        return self.db.query({feature_name.title()}).filter({feature_name.title()}.id == item_id).first()
    
    async def list(self, skip: int = 0, limit: int = 100) -> List[{feature_name.title()}]:
        """List all records"""
        return self.db.query({feature_name.title()}).offset(skip).limit(limit).all()
    
    async def update(self, item_id: int, data):
        """Update record"""
        db_item = await self.get(item_id)
        if db_item:
            for key, value in data.dict(exclude_unset=True).items():
                setattr(db_item, key, value)
            self.db.commit()
            self.db.refresh(db_item)
        return db_item
    
    async def delete(self, item_id: int):
        """Delete record"""
        db_item = await self.get(item_id)
        if db_item:
            self.db.delete(db_item)
            self.db.commit()
        return db_item
'''
    
    repo_file.write_text(repo_content)
    print(f"✓ Created repository: {repo_file}")
    
    # Update main.py to include new router
    update_main_routes(project_path, feature_name)
    
    # Update dependencies if specified
    if modifications.get('dependencies'):
        update_requirements(project_path, modifications['dependencies'])

def update_main_routes(project_path, feature_name):
    """Update main.py to include new routes"""
    main_file = Path(project_path, 'app/main.py')
    if main_file.exists():
        content = main_file.read_text()
        
        # Add import
        import_line = f"from app.api.routes import {feature_name}"
        if import_line not in content:
            # Find the last import line
            lines = content.split('\n')
            last_import_idx = 0
            for i, line in enumerate(lines):
                if line.startswith('from ') or line.startswith('import '):
                    last_import_idx = i
            
            lines.insert(last_import_idx + 1, import_line)
            content = '\n'.join(lines)
        
        # Add router
        router_line = f"app.include_router({feature_name}.router)"
        if router_line not in content:
            # Find where to add router (after app creation)
            if 'app = FastAPI' in content:
                content = content.replace(
                    'app = FastAPI(',
                    f'app = FastAPI(\n'
                )
                # Add router after app creation
                lines = content.split('\n')
                for i, line in enumerate(lines):
                    if 'app = FastAPI' in line:
                        # Find the closing parenthesis
                        j = i
                        while j < len(lines) and ')' not in lines[j]:
                            j += 1
                        lines.insert(j + 2, f"\n{router_line}")
                        break
                content = '\n'.join(lines)
        
        main_file.write_text(content)
        print(f"✓ Updated main.py with {feature_name} routes")

def update_requirements(project_path, dependencies):
    """Update requirements.txt with new dependencies"""
    req_file = Path(project_path, 'requirements.txt')
    if req_file.exists():
        current = req_file.read_text()
        new_deps = []
        
        for dep in dependencies:
            if dep and dep not in current:
                new_deps.append(dep)
        
        if new_deps:
            with open(req_file, 'a') as f:
                f.write('\n' + '\n'.join(new_deps) + '\n')
            print(f"✓ Added {len(new_deps)} dependencies to requirements.txt")

def main():
    if len(sys.argv) < 2:
        print("Usage: modify-python.py <modifications.json>")
        sys.exit(1)
    
    modifications_file = sys.argv[1]
    with open(modifications_file) as f:
        modifications = json.load(f)
    
    project_path = os.getcwd()
    framework = detect_python_framework(project_path)
    
    print(f"Detected framework: {framework}")
    print(f"Applying modifications: {modifications['modification_type']}")
    
    if framework == 'fastapi':
        add_fastapi_endpoint(project_path, modifications)
    elif framework == 'flask':
        print("Flask modifications not yet implemented")
    elif framework == 'django':
        print("Django modifications not yet implemented")
    else:
        print(f"Unknown framework in {project_path}")
        sys.exit(1)
    
    print("\n✅ Modifications applied successfully")

if __name__ == '__main__':
    main()
